package br.nocclaro.autoalert.domain;

public enum IdentificadorVulnerabilidade {

    SERVICO_LDAP_HABILITADO,
    SERVICO_QOTD_HABILITADO,
    SERVICO_CHARGEN_HABILITADO,
    SERVICO_MDNS_MULTICAST_DNS_HABILITADO,
    SERVIDORES_DNS_RECURSIVOS_ABERTOS,
    SERVICO_NETBIOS_HABILITADO,
    SERVICO_SSDP_UPNP_HABILITADO,
    SERVICO_MEMCACHED_HABILITADO,
    SERVICO_SNMP_HABILITADO,
    SERVIDORES_NTP_MAL_CONFIGURADOS,
    SERVICO_DEVICE_DISCOVERY_HABILITADO,
    SERVICO_PORTMAP_HABILITADO
}
